matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

language: minimal

script:
  - echo "==> Tests"
  - sudo ./tests/run

deploy:
  provider: launchpad
  edge: true
