#!/bin/sh

# Report the names of the processes (or QEMU VMs) using deleted libraries or binaries.
# Copyright (C) 2014-2017 Simon Deziel <simon@sdeziel.info>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Explicitly set the PATH to that of ENV_SUPATH in /etc/login.defs and unset
# various other variables. For details, see:
# https://wiki.ubuntu.com/SecurityTeam/AppArmorPolicyReview#Execute_rules
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export ENV=
export CDPATH=
export LC_ALL="C"

SCRIPT_NAME="$(basename "$0")"

p_error () {
  echo "Error: $1" >&2
  exit 1
}

usage () {
  cat << EOF
Copyright (C) 2014-2017 Simon Deziel

Report the names of the processes (or QEMU VMs) using deleted libraries or binaries.

Usage:
  $SCRIPT_NAME [--qemu-names]
EOF
  exit 0
}

# Check arguments
QEMU_NAMES=0
[ "$#" -gt 1 ] && usage
if [ "$#" -eq 1 ]; then
  [ "$1" != "--qemu-names" ] && usage
  QEMU_NAMES=1
fi

# Check if /proc/*/maps are readable by testing with PID=1
cd "/proc"
cat "1/maps" >/dev/null 2>&1 || p_error "Unable to read /proc/1/maps, are you running $SCRIPT_NAME with root privileges?"

GREP_RE='[[:space:]]((/.+)?/(lib|s?bin/)[^/]+ \(deleted\)|\(deleted\)(/.+)?/(lib|s?bin/)[^/]+)$'

# report names of VM running outdated QEMU
if [ "$QEMU_NAMES" -eq 1 ]; then
  pgrep -a ^qemu-system-.+ | sed 's/^\([0-9]\+\).\+ -name \([^ ]\+\).*/\1 \2/' | while read -r pid vmname; do
    grep -q -m1 -E "$GREP_RE" "$pid/maps" 2>/dev/null && echo "$vmname"
  done
  exit
fi

# Check if we can use a fast path (/proc/$pid/comm available and no prelink)
if [ -e "1/comm" ] && [ ! -x "$(/usr/bin/which prelink 2>/dev/null)" ]; then # fast path
  # shellcheck disable=SC2046
  true | sort -u $(grep -m1 -lE "$GREP_RE" [0-9]*/maps 2>/dev/null | sed 's/maps$/comm/')
else # slow path
  grep -HE "$GREP_RE" [0-9]*/maps 2>/dev/null | grep -vF ".#prelink#." | cut -d/ -f1 | sort -u | while IFS= read -r pid; do
    sed -n "/^Name:[[:space:]]\+/ s/^Name:[[:space:]]\+//p;q" "$pid/status" 2>/dev/null
  done | sort -u
fi
